### ISSUE TITLE
Implement DataLayer

### ISSUE THREAD

**Issue by mastorm** [discord-csharp/Contacts#3]
EF Core 1.1 featuring SQLite could be used as a datalayer.

**Comment by jmazouri** [comment]
According to this article, many migration features are missing when using sqlite with EF Core (though not because of EF). Something to note if we choose to go with that vs. a lighter data layer like Dapper or PetaPoco.

https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations

**Comment by markusamshove** [comment]
I'm using Dapper + FluentMigrator in a current project which also uses SQLite and can recommend that.
It's also easy to test against the DataLayer when using SQLite and some sort of Migrationtool.

**Comment by mastorm** [comment]
@MarkusAmshove wouldnt that force us into database first?

**Comment by jmazouri** [comment]
FluentMigrator handles database creation, but you have to manually create up/down migration scripts w/ their fluent API (hence the name).

**Comment by markusamshove** [comment]
Also I was referencing the wrong librarie, I meant Simple.Migration:

https://github.com/canton7/Simple.Migrations

since FluentMigrator is a bit outdated. I always get those two wrong :-)

You do have to write SQL for migrations, but if you want to go with Dapper you have it both in a idomatic way.

The nice thing about migrations + Dapper with SQLite is that you can easily set up your dev environment

**Comment by ghost** [comment]
Implemented a PostgreSQL Data Layer via my PR, let me know if there is any corrections needed to be made.

**Comment by jmazouri** [comment]
Resolved via #29
